- hosts: all
  user: azureuser
  tasks:
    - name: create new deployment
      command: kubectl --kubeconfig=/home/azureuser/.kube/config apply -f /home/azureuser/Deployment.yml
    - name: create new service
      command: kubectl --kubeconfig=/home/azureuser/.kube/config apply -f /home/azureuser/Service.yml
