apiVersion: v1
kind: Service
metadata:
  name: vince
spec:
  selector:
    app.kubernetes.io/name: 
  ports:
    - protocol: 
      port: 8080
      targetPort: 80
      nodePort: 31200
  selector:
    app: vince
  type: LoadBalancer
